[pytest]
asyncio_mode = auto
testpaths = tests
addopts = -v --tb=short --disable-warnings
filterwarnings =
    ignore::DeprecationWarning:passlib
    ignore::DeprecationWarning:argon2
    ignore::DeprecationWarning:crypt